### ISSUE TITLE
[Feature Request] 修改或自定义事件/心情的时间

### ISSUE THREAD

**Issue by tonghuix** [maxiee/HeartBeat#2]
如题。有时候无法当时记录某一时刻的事件或者心情，还比如啪啪啪当时不可能记录，只能是第二天醒来才会总结。而此时就造成日期时间的错误了。

因此希望可以提供日期和时间的修改功能，进而可以更好的记录下生活的瞬间。

**Comment by maxiee** [comment]
我会在后续版本中加入。

**Comment by maxiee** [comment]
功能已完成，将会在新版本中发布。
