### ISSUE TITLE
[Feature Request] 心情支持添加图片和录音

### ISSUE THREAD

**Issue by tonghuix** [maxiee/HeartBeat#3]
有时来不及打字记录的时候，往往就拍照了，希望可以将附加图片功能加上。

另外是否可以支持录音功能，类似微信的那种，这样就可以将即时心情录制下来。也方便懒得手机打字时使用。

**Comment by maxiee** [comment]
添加图片功能已在设计当中。录音是个好主意！

**Comment by maxiee** [comment]
添加图片已完成。添加录音还要再研究研究…

**Comment by tonghuix** [comment]
好赞！
