### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by YanceyWang** [maxiee/HeartBeat#5]
Error:A problem occurred configuring project ':app'.
> Could not download glide.jar (com.github.bumptech.glide:glide:3.6.1)
   > Could not get resource 'https://jcenter.bintray.com/com/github/bumptech/glide/glide/3.6.1/glide-3.6.1.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/github/bumptech/glide/glide/3.6.1/glide-3.6.1.jar'.
         > peer not authenticated

**Comment by maxiee** [comment]
What IDE and version do you use?

**Comment by YanceyWang** [comment]
android studio 1.4

**Comment by YanceyWang** [comment]
my network goes wrong...
