### ISSUE TITLE
Add button sometimes disappears

### ISSUE THREAD

**Issue by JokerQyou** [maxiee/HeartBeat#8]
Follow the following steps to reproduce:

- Enter the detail page of an event by clicking on it after launched the app
- On the detail page, long press one of the thoughts, let's say the first thought, to enter the editing page
- Press the "Done" button on the top right corner
- Now you're back to the event detail page, but instead of seeing all the thoughts listed below the event, you can see only the first thought is there. The actual list area overflowed, and the other thoughts are hidden.
- Now touch and scroll the first thought, bring it to top, so we can see other thoughts
- As soon as you scroll the first thought to the top, the list went back to normal, and the "Add" button that was previously on the right bottom of the app is now gone.

**Comment by maxiee** [comment]
Yes they are actually 2 separated problems:

1. The overflowed list: The overflowed  area is the area keyboard occupied. When backing from the thought editing page, this area isn't released until you do a scrolling. I'm looking for the solution for a long time.

2. The disappeared "Add" button: Sometimes the "Add" button may not reappear when scrolling. This is a known, too.

I'll keep finding the reason of these problems.
